language: python

python:
    - 3.6
    - 3.7
    - 3.8
    - 3.9
    - pypy

env:
    global:
        - PYFLAKES_NODOCTEST=1
    matrix:
        - TWISTED=Twisted==16.4
        - TWISTED=Twisted==17.9
        - TWISTED=Twisted==18.9
        - TWISTED=Twisted==20.3
        - TWISTED=Twisted==21.2
        - TWISTED=https://github.com/twisted/twisted/archive/trunk.zip

install:
    - pip install -q $TWISTED
    - pip install .[dev]

script:
    - pyflakes wokkel twisted
    - trial wokkel
